server:
  port: 8092
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.190.128
  rabbitmq:
    addresses: 192.168.190.128
    host: 5601
    username: lzzzzz
    password: lzzzzz
    virtual-host: /lz
jwt:
  token:
    pubKeyPath: E:\Project\rsa\rsa.pub
    cookieName: gmall-token
    userKey: user-key
    expireTime: 77760000